app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', function() use($locale)
{
	return Redirect::to('/'.$locale);
});
/*Route::get('/' .$locale, function() use($locale)
{
	if(Request::header('referer'))
	{
		$refererUrl = Request::header('referer');
		$refererUrl = preg_replace("/\/(en|vi)\//", "/$locale/", $refererUrl);
		return Redirect::to($refererUrl);
	} else {
		return Redirect::to('/'.$locale);
	}
	die();
});*/

// App::missing(function($exception)
// {
//     return Response::view('missing', array(), 404);
// });

app/controllers/Admin/EmployerController.php
<?php
use App\DTT\Forms\AdminNTDCreate;
class EmployerController extends \BaseController {

	/**
	 * Display a listing of the resource.
	 * GET /employer
	 *
	 * @return Response
	 */
	public function index()
	{
		//
		$employers = User::orderBy('id', 'desc');
		return View::make('admin.employers.index', compact('employers'));
	}
	public function datatables()
	{
		$page=0;
		if (Request::ajax()) {
			$page=(Input::get('iDisplayStart'));
		}
		$user=AdminAuth::getUser();
		if(in_array('admin_full',json_decode($user->permissions)))
			{
			$employers = NTD::join('companies','employers.id','=','companies.ntd_id')
			->leftjoin('admin_info','employers.admin_info_id','=','admin_info.id')
			->select('employers.id as ckid', 'employers.id as id', 'companies.company_name as company_name', 'employers.email','employers.phone_number', 'employers.created_at', 'employers.is_active', 'employers.id as idd', 'employers.id as ids','admin_info.username as cskh')->with('job')->orderBy('employers.id','desc');

			}
		else
		{
			$employers = NTD::join('companies','employers.id','=','companies.ntd_id')
			->join('admin_info','employers.admin_info_id','=','admin_info.id')
			->select('employers.id as ckid', 'employers.id as id', 'companies.company_name as company_name', 'employers.email','employers.phone_number', 'employers.created_at', 'employers.is_active', 'employers.id as idd', 'employers.id as ids','admin_info.username as cskh')->with('job')->orderBy('employers.id','desc')->where('employers.admin_info_id',$user->id);
		}
		$active = Input::get('active');
		 	
		

		if($active!=null) {$employers->whereIsActive($active);}

		return Datatables::of($employers)

		->edit_column('ckid', '<th class="center">
															<label class="pos-rel">
																<input type="checkbox" class="ace" />
																<span class="lbl"></span>
															</label>
														</th>
		')
		->edit_column('company_name','<a class="" href="{{URL::route("admin.employers.edit",$id)}}?page={{'.$page.'}}&web=emp_index" title="Edit">{{$company_name}}</a>')
		->remove_column('id')
		->edit_column('is_active', '@if($is_active==1)<span class="label label-success">Kích hoạt</span>@else <span class="label label-info">Không kích hoạt</span>@endif')
		->edit_column('idd', '{{ HTML::link(URL::route("admin.jobs.index", ["id"=>$id]), count($job) ) }}')

		->edit_column('ids', '
			{{ Form::open(array("method"=>"delete", "route"=>array("admin.employers.destroy", $id) )) }}
			
			<a class="btn btn-xs btn-info" href="{{URL::to("admin/order/package-employer/$id")}}" title="Chỉnh sửa dịch vụ cho nhà tuyển dụng"><i class="ace-icon fa fa-cogs bigger-120"></i></a> 
			<button class="btn btn-xs btn-danger" onclick="return confirm(\'Are you sure you want to delete ?\');" type="submit" title="Delete"><i class="ace-icon fa fa-trash-o bigger-120"></i></button>
			{{ Form::close() }}
			')
		->edit_column('cskh','{{$cskh}}')
		->make();
	}

	/**
	 * Show the form for creating a new resource.
	 * GET /employer/create
	 *
	 * @return Response
	 */
	public function create()
	{
		//
		return View::make('admin.employers.create');
	}

	/**
	 * Store a newly created resource in storage.
	 * POST /employer
	 *
	 * @return Response
	 */
	public function store()
	{
		//
		 
		$data = Input::only('email','password','full_name','address','position','country_id','province_id','phone_number','is_active');
		$data1=Input::only('company_name','work_type','company_address','display_logo','full_description','work_field','giolamviec','chonchungtoi','started_year','quymocty','video_link','google_map'); 
		$data1['contact_name']=Input::get('full_name');

		$rules = array(
			'email'			=>	'required|email|unique:employers,email',
			'password'		=>	'min:3',
			'is_active'		=>	'in:0,1',
			
		);

		$messages = array(
			'email.required'	=>	'Email không được để trống.',
			'email'		=>	'Email không đúng định dạng.',
			'unique'	=>	':attribute đã tồn tại, vui lòng chọn tên khác',
			'min'		=>	':attribute tối thiểu là :min kí tự.',
			
		);
		$validator = Validator::make($data, $rules, $messages);

		$rules1=array(
			'company_name'	=>	'required',
			'filelogo'		=>	'mimes:jpeg,bmp,png|max:100',
			'image1'		=>	'mimes:jpeg,bmp,png|max:1000',
			'image2'		=>	'mimes:jpeg,bmp,png|max:1000',
			'image3'		=>	'mimes:jpeg,bmp,png|max:1000',
			'image4'		=>	'mimes:jpeg,bmp,png|max:1000',
			'image5'		=>	'mimes:jpeg,bmp,png|max:1000',
			);
		$messages1=array(
			'company_name.required'	=>	'Tên công ty không được để trống.',
			'filelogo.mimes'			=>	'Logo không đúng định dạng',
			'image1.mimes'			=>	'Hình ảnh 1 không đúng định dạng',
			'image2.mimes'			=>	'Hình ảnh 2 không đúng định dạng',
			'image3.mimes'			=>	'Hình ảnh 3 không đúng định dạng',
			'image4.mimes'			=>	'Hình ảnh 4 không đúng định dạng',
			'image5.mimes'			=>	'Hình ảnh 5 không đúng định dạng',
			'filelogo.max'			=>	'Dung lượng logo quá lớn',
			'image1.max'			=>	'Hình ảnh 1 dung lượng quá lớn',
			'image2.max'			=>	'Hình ảnh 2 dung lượng quá lớn',
			'image3.max'			=>	'Hình ảnh 3 dung lượng quá lớn',
			'image4.max'			=>	'Hình ảnh 4 dung lượng quá lớn',
			'image5.max'			=>	'Hình ảnh 5 dung lượng quá lớn',
			);

		$validator1 = Validator::make($data1, $rules1, $messages1);
		
		if($validator1->fails())
		{
			return Redirect::back()->withInput()->withErrors($validator);
		}

		if($validator->fails())
		{
			return Redirect::back()->withInput()->withErrors($validator);
		} else {

			if (Input::hasFile('filelogo')) {
				$path = Config::get('app.upload_path').'companies/logos/';
				Input::file('filelogo')->move($path, Input::file('filelogo')->getClientOriginalName());
				$data1['logo'] = Input::file('filelogo')->getClientOriginalName();
			}
			 
			$path = Config::get('app.upload_path').'companies/images/';
			$company_images = array();
			$hasImage = false;
			for ($i=1; $i <= 5; $i++) { 
				if (Input::hasFile('image'.$i)) {
					Input::file('image'.$i)->move($path, Input::file('image'.$i)->getClientOriginalName());
					$company_images[] = Input::file('image'.$i)->getClientOriginalName();
					$hasImage = true;
				} else {
					$company_images[] = "";
				}
				unset($data1['image'.$i]);
				
			}
			if($hasImage) $data1['company_images'] = json_encode($company_images);
			//Company::where('ntd_id', Auth::id())->update($params);



			if($data['password'] == '') {
				return Redirect::back()->withInput()->withErrors('Nhập password');
			} else {
				$data['password'] = Hash::make($data['password']);
			}
			 
			$ntd = NTD::create($data);
			if($ntd) {
				$company = new Company;
				$company->ntd_id = $ntd->id;
				$company->save();
				Company::where('ntd_id', $ntd->id)->update($data1);

				return Redirect::route('admin.employers.index')->withSuccess('Thêm mới NTD thành công.');
			}
			else
				return Redirect::back()->withInput()->withErrors('Lỗi khi thêm mới');
			//Company::where('ntd_id', $id)->update($data1);
			//$ntd = NTD::where('id', $id)->update($data);
			//return Redirect::route('admin.employers.index',array('page'=>$page))->withSuccess('Lưu thông tin thành công.');
		}
	}

	/**
	 * Display the specified resource.
	 * GET /employer/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 * GET /employer/{id}/edit
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function getEditEmployers($page,$id)
	{
		//
		$com = NTD::whereId($id)->with('company')->first();

		if(!$com) return Response::make('Không tìm thấy NTD');
		return View::make('admin.employers.edit', compact('com'));
	}


	public function edit($id)
	{
		//
		$com = NTD::whereId($id)->with('company')->first();

		if(!$com) return Response::make('Không tìm thấy NTD');
		return View::make('admin.employers.edit', compact('com'));
		/*$employer = NTD::find($id);
		if(!$employer) return Response::make('Không tìm thấy NTD');
		return View::make('admin.employers.edit', compact('employer'));*/
	}


	/**
	 * Update the specified resource in storage.
	 * PUT /employer/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)// của resource
	{
		 

		$data = Input::only('email','password','full_name','address','position','country_id','province_id','phone_number','is_active');
		 

		$data1=Input::only('company_name','work_type','company_address','display_logo','full_description','work_field','giolamviec','chonchungtoi','started_year','quymocty','video_link','google_map');

		//unset($data['_token']);
		//unset($data['_method']);
		$rules = array(
			'email'			=>	'required|email|unique:employers,email,'.$id,
			'password'		=>	'min:3',
			'is_active'		=>	'in:0,1',
			
		);

		$messages = array(
			'email.required'	=>	'Email không được để trống.',
			'email'		=>	'Email không đúng định dạng.',
			'unique'	=>	':attribute đã tồn tại, vui lòng chọn tên khác',
			'min'		=>	':attribute tối thiểu là :min kí tự.',
			
		);
		$validator = Validator::make($data, $rules, $messages);

		$rules1=array(
			'company_name'	=>	'required',
			'filelogo'		=>	'mimes:jpeg,bmp,png|max:100',
			'image1'		=>	'mimes:jpeg,bmp,png|max:1000',
			'image2'		=>	'mimes:jpeg,bmp,png|max:1000',
			'image3'		=>	'mimes:jpeg,bmp,png|max:1000',
			'image4'		=>	'mimes:jpeg,bmp,png|max:1000',
			'image5'		=>	'mimes:jpeg,bmp,png|max:1000',
			);
		$messages1=array(
			'company_name.required'	=>	'Tên công ty không được để trống.',
			'filelogo.mimes'			=>	'Logo không đúng định dạng',
			'image1.mimes'			=>	'Hình ảnh 1 không đúng định dạng',
			'image2.mimes'			=>	'Hình ảnh 2 không đúng định dạng',
			'image3.mimes'			=>	'Hình ảnh 3 không đúng định dạng',
			'image4.mimes'			=>	'Hình ảnh 4 không đúng định dạng',
			'image5.mimes'			=>	'Hình ảnh 5 không đúng định dạng',
			'filelogo.max'			=>	'Dung lượng logo quá lớn',
			'image1.max'			=>	'Hình ảnh 1 dung lượng quá lớn',
			'image2.max'			=>	'Hình ảnh 2 dung lượng quá lớn',

app/controllers/NTD/CandidateController.php
<?php 
namespace NTD;
use View, Redirect, Input, EFolder, Job, Auth, Response, Application,RSFolder;
class CandidateController extends \Controller {
	public function __construct()
	{
		$job_name = Job::where('ntd_id', Auth::id())->with('application')->get();
		View::share('job_name', $job_name);
		$folders = EFolder::where('ntd_id', Auth::id())->with('application')->orderBy('id', 'desc')->get();
		View::share('folders', $folders);
		$viewed = \OrderDetail::where('ntd_id', Auth::id())->count();
		View::share('viewed', $viewed);
	}
	public function getIndex()
	{
		return Redirect::route('employers.candidates.job', 'all');
	}
	public function getCongViec($id = false)
	{
		$apply = Application::orderBy('id', 'desc')
		->where('left_status', 0)
		->whereHas('job', function($q) {
			$q->where('ntd_id', Auth::id());
		});
		if(is_numeric($id))
		{
			$apply->whereHas('job', function($q) use($id) {
				$q->where('id', $id);
			});
		}

		$apply = $apply->paginate(10);

		  
		
		return View::make('employers.candidates.job', compact('apply'))->with('job_id', $id);
	}
	public function getThuMuc($id = false)
	{
		if($id)
		{
			$apply = Application::orderBy('id', 'desc')->where('nav_id', 2);
			if(is_numeric($id))
			{
				$apply = RSFolder::where('ntd_id', Auth::id())->where('left_status', 0)->where('folder_id', $id)->orderBy('id','desc')->paginate(10);
				$isFolder = 1;
				return View::make('employers.candidates.folder', compact('apply', 'isFolder'))->with('folder_id', $id);
			} else {
				$apply = RSFolder::where('ntd_id', Auth::id())->where('left_status', 0)->orderBy('id','desc');
			}
			$isFolder = 0;
			$apply = $apply->paginate(10);
			return View::make('employers.candidates.folder', compact('apply', 'isFolder'))->with('folder_id', $id);
		}
		return Redirect::route('employers.candidates.folder', 'all');
	}
	public function postJob()
	{
		if(Input::get('act') == 'luu') // luu thu muc
		{
			if(Input::get('valid'))
			{
				//check xem cv do da co o folder can di chuyen chua
				$cvs = Input::get('valid');
				$rsfolder = RSFolder::where('folder_id', Input::get('val'))->get();
				if(count($rsfolder))
				{
					foreach ($rsfolder as $key => $value) {
						if(in_array($value->cv_id, $cvs))
						{
							$value->delete(); 
						}
					}
				}
				foreach ($cvs as $key => $value) {
					RSFolder::create([
							'ntd_id'	=>	Auth::id(),
							'folder_id'	=>	Input::get('val'),
							'cv_id'		=>	$value,
							'status'	=>	1
						]);
				}

				//var_dump(Input::all());die();
				
			}
			return Redirect::back()->with('success', 'Cập nhật thư mục thành công');
		}
		if(Input::get('act') == 'danhgiaall') // luu thu muc
		{
			if(Input::get('valid'))
			{
				$update = Application::whereIn('id', Input::get('valid'))
				->whereHas('job', function($q) {
					$q->where('ntd_id', Auth::id());
				})
				->update(['status'=>Input::get('val')]);
			}
			return Redirect::back()->with('success', 'Cập nhật trạng thái thành công');
		}
		if(Input::get('act') == 'xoaall') // luu thu muc
		{
			$check = Application::whereIn('cv_id', Input::get('valid'))
			->whereHas('job', function($q) {
				$q->where('ntd_id', Auth::id());
			})->lists('id');
			Application::destroy($check);
			//xoa application thi phai xoa ca o folder
			$check = RSFolder::whereIn('cv_id', Input::get('valid'))
			->where('ntd_id', Auth::id())->lists('id');
			RSFolder::destroy($check);

			return Redirect::back()->with('success', 'Xóa thành công');
		}
	}
	public function postThuMuc($id = false)
	{
		if(Input::get('act') == 'luu') // luu thu muc
		{
			if(Input::get('valid'))
			{
				//check xem cv do da co o folder can di chuyen chua
				$cvs = Input::get('valid');
				$rsfolder = RSFolder::find(Input::get('val'));
				if(count($rsfolder))
				{
					if(in_array($rsfolder->cv_id, $cvs))
					{
						$rsfolder->delete();
					}
				}
				$update = RSFolder::whereIn('id', Input::get('valid'))
				->where('ntd_id', Auth::id())
				->update(['folder_id'=>Input::get('val')]);
			}
			//return 1;
			return Redirect::back()->with('success', 'Cập nhật thư mục thành công');
		}
		if(Input::get('act') == 'danhgiaall') // luu thu muc
		{
			if(Input::get('valid'))
			{
				$update = RSFolder::whereIn('id', Input::get('valid'))
				->where('ntd_id', Auth::id())
				->update(['status'=>Input::get('val')]);
			}
			return Redirect::back()->with('success', 'Cập nhật trạng thái thành công');
		}
		if(Input::get('act') == 'xoaall') // luu thu muc
		{

			if (Input::get('valid')==null) {
				return Redirect::back()->withInput()->withErrors('Chọn mục để xóa'); 
			}
			else
			{
				$check = RSFolder::whereIn('id', Input::get('valid'))
				->where('ntd_id', Auth::id())->lists('id');

				RSFolder::destroy($check);
				return Redirect::back()->with('success', 'Xóa thành công');
			}
		}
	}
	public function getQuanLyThuMuc()
	{
		$fds = EFolder::orderBy('created_at', 'desc')->where('ntd_id', Auth::id())->with('application')->paginate(10);
		return View::make('employers.candidates.folder_list', compact('fds'));
	}
	public function postTaoThuMuc()
	{
		if(Input::get('folderName'))
		{
			$folder_name = substr(Input::get('folderName'),0,40);
			\TaskLog::create(['ntd_id'=>Auth::id(), 'action_type'=>'create_folder','target'=>'Tạo thư mục: ' . Input::get("folderName") ]);
			$created = EFolder::firstOrCreate(['folder_name'=>$folder_name, 'ntd_id'=>Auth::id()]);
			
		}
		return Redirect::back()->with('success', 'Tạo folder thành công !');
	}
	public function postSuaThuMuc()
	{
		$folder = EFolder::where('ntd_id', Auth::id())
				->where('id', Input::get('folder_id'))
				->first();
		$folder->folder_name = substr(Input::get('folder_name'), 0, 40);
		$folder->save();
		return Response::json(['success'=>true]);
	}
	public function getXoaThuMuc($id = false)
	{
		if($id)
		{
			$folder = EFolder::where('ntd_id', Auth::id())
				->where('id', $id)
				->first();
			if($folder->application->count() == 0) {
				\TaskLog::create(['ntd_id'=>Auth::id(), 'action_type'=>'del_folder','target'=>'Xóa thư mục: ' . $folder->folder_name ]);
				$folder->delete();
			}


		}
		return Redirect::back()->with('success', 'Xóa folder thành công !');
	}
	public function getHoSoDaXoa()
	{
		$apply = Application::orderBy('id', 'desc')
		->where('nav_id', 3)
		->whereHas('job', function($q) {
			$q->where('ntd_id', Auth::id());
		});
		
		$jobs = $apply->paginate(10);
		return View::make('employers.candidates.deleted', compact('jobs'));
	}
	public function getDanhSachTuChoi()
	{
		$apply = Application::orderBy('id', 'desc')
		->where('nav_id', 4)
		->whereHas('job', function($q) {
			$q->where('ntd_id', Auth::id());
		});
		
		$jobs = $apply->paginate(10);
		return View::make('employers.candidates.blocked', compact('jobs'));
	}
	public function getReport()
	{

	}
	
	public function getTest()
	{
		
	}
	public function getDanhSachHoSoDaXem()
	{
		$detail = \OrderDetail::where('ntd_id', Auth::id())->orderBy('id', 'desc')->paginate(10);
		return View::make('employers.candidates.viewed', compact('detail'));
	}




}

app/views/employers/candidates/index.blade.php
@extends('layouts.employer')
@section('title') Quản lý hồ sơ @stop
@section('content')
<section class="boxed-content-wrapper clearfix">
		<div class="container">
			<aside id="sidebar" class="col-sm-3">
				@include('includes.employers.candidates_navbar')
			</aside>
			
			<section id="content" class="pull-right right">
				<div class="header-image">
					HỒ SƠ <span class="text-blue">ỨNG VIÊN</span>
				</div>
				<div class="boxed">
					<div class="heading-image">
						<h2 class="text-orange">Danh sách ứng viên nộp hồ sơ ứng tuyển</h2>
					</div>
					<div class="filter">
						<label>Chú ý: Hồ sơ sẽ bị xóa khỏi trang Quản Lý Tuyển Dụng sau 13 tháng
					</label>
					</div>
					<table class="table table-bordered table-blue-bordered white rs-table">
						<thead>
							<tr>
								<th>Tên ứng viên</th>
								<th>Chức danh</th>
								<th>Ngày nhận</th>
								<th>Tình trạng</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td><a href="#" class="text-blue decoration"><strong>Trần Anh Điệp</strong></a></td>
								<td>Nhân viên IT</td>
								<td>23-05-2015</td>
								<td>Đã chọn</td>
							</tr>
							<tr>
								<td><a href="#" class="text-blue decoration"><strong>Trần Anh Điệp</strong></a></td>
								<td>Nhân viên IT</td>
								<td>23-05-2015</td>
								<td>Đã chọn</td>
							</tr>
							<tr>
								<td><a href="#" class="text-blue decoration"><strong>Trần Anh Điệp</strong></a></td>
								<td>Nhân viên IT</td>
								<td>23-05-2015</td>
								<td>Đã chọn</td>
							</tr>
							<tr>
								<td><a href="#" class="text-blue decoration"><strong>Trần Anh Điệp</strong></a></td>
								<td>Nhân viên IT</td>
								<td>23-05-2015</td>
								<td>Đã chọn</td>
							</tr>
						</tbody>
					</table>
				</div>		
			</section>
		</div>
	</section>
@stop

app/views/employers/candidates/respond.blade.php
@extends('layouts.employer')
@section('title') Phản hồi của ứng viên - VnJobs @stop
@section('content')
	<section class="boxed-content-wrapper clearfix">
		<div class="boxed">
			<div class="heading-image">
				<h2 class="text-orange">Phản hồi của ứng viên</h2>
			</div>			
			<table class="table table-bordered table-blue-bordered white rs-table">
				<thead>
					<tr>
						<th>Tên ứng viên</th>
						<th>Link đến hồ sơ ứng viên</th>
						<th>Nội dung phản hồi</th>
						<th>Tiêu đề phản hồi</th>
						<th>Ngày phản hồi</th>
						<th>Hành động</th>
					</tr>
				</thead>
				<tbody>
					@if(count($responds))
					@foreach($responds as $v)
					<tr>
						<td id="td0_{{$v->ntv_id}}">{{ $v->ntv->first_name }} {{ $v->ntv->last_name }}</td>
						<td id="td1_{{$v->ntv_id}}">@if($v->ntv->resume->count() > 0){{ HTML::link(URL::route('employers.search.resumeinfo', $v->ntv->resume->first()->id), null, ['class'=>'text-blue'] ) }}@else @endif</td>
						<td>{{ $v->content }}</td>
						<td>{{ $v->title }}</td>
						<td>{{ $v->submited_date }}</td>
						<td>
							@if($v->user_submit == Auth::id())
							Bạn trả lời
							@else
							<button type="button" class="btn btn btn-lg bg-orange bg-green" onclick="showmodal({{ $v->ntv_id }});">Phản hồi</button>
							@endif
						</td>
					</tr>
					@endforeach
					@else
					<tr>
						<td colspan="5">Không có phản hồi nào</td>
					</tr>
					@endif

					
				</tbody>
			</table>
		</div>
		<!-- <div class="boxed">
			<div class="heading-image">
				<h2 class="text-orange">Email mẫu</h2>
			</div>	
			<label class="h3"><strong>Bạn có <span class="text-orange">1 Email mẫu</span></strong></label>
			<table class="table table-bordered table-blue-bordered white">
				<thead>
					<tr>
						<th>Email mẫu</th>
						<th>Loại</th>
						<th>Ngày cập nhật</th>
						<th>Thao tác</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td colspan="4">
							Tạo email mẫu 1 lần để dùng nhiều lần và tiết kiệm thời gian liên lạc với ứng viên!<br>
							"Để hỗ trợ quý khách tốt nhất, chúng tôi đã tạo 4 mẫu thư phản hồi mặc định. Nhấn vào tạo email mẫu để tạo email mẫu phù hợp với nhu cầu cụ thể của quý công ty."
						</td>
					</tr>
				</tbody>
			</table>
			<button type="button" class="btn btn-lg bg-orange">Tạo email mẫu mới</button>
		</div> -->
	</section>


	<div class="modal fade" id="modalRespond">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title">Gửi phản hồi lại ứng viên</h4>
				</div>
				<div class="modal-body">
					<form action="" method="POST" class="form-horizontal" role="form" onsubmit="return sendRespond();">
						<div id="result-send"></div>
						<div class="form-group">
							<label for="input" class="col-sm-2 control-label">Ứng viên:</label>
							<div class="col-sm-10">
								<a href="#" target="_blank" id="ung-vien-ten"></a>
							</div>
						</div>
						<div class="form-group">
							<label for="inputSubject" class="col-sm-2 control-label">Tiêu đề:</label>
							<div class="col-sm-10">
								<input type="text" name="subject" id="inputSubject" class="form-control" value="" required="required">
							</div>
						</div>
						<div class="form-group">
							<label for="textareaContent" class="col-sm-2 control-label">Nội dung:</label>
							<div class="col-sm-10">
								<textarea name="content" id="textareaContent" class="form-control" rows="5" required="required"></textarea>
							</div>
						</div>
						<input type="hidden" name="ntv_id" id="ntv_id" class="form-control" value="">
							<div class="form-group">
								<div class="col-sm-10 col-sm-offset-2">
									<button type="submit" class="btn btn-lg bg-orange bg-green">Gửi phản hồi</button>
									<button type="submit" class="btn btn-lg bg-orange" data-dismiss="modal">Đóng</button>
								</div>
							</div>
					</form>
				</div>
				
			</div>
		</div>
	</div>
@stop

@section('script')
	<script type="text/javascript">
	var sendRespond = function()
	{
		var subject = $('#inputSubject').val();
		var content = $('#textareaContent').val();
		var ntv_id = $('#ntv_id').val();
		$.ajax({
			url: '{{ URL::route('employers.report.sendrespond') }}',
			type: 'POST',
			data: {ntv_id: ntv_id, subject: subject, content: content},
			dataType: 'json',
			success: function(json)
			{
				if(json.has)
				{
					$('#result-send').html('<div class="alert alert-success">Gửi phản hồi thành công</div>');
					setTimeout(function(){ window.location.href = '{{ URL::route('employers.report.respond') }}'; }, 1000);
				} else {
					$('#result-send').html('<div class="alert alert-danger">Không thể gửi phản hồi tới ứng viên</div>');
					setTimeout(function(){ $('#result-send').html(''); }, 3000);
				}
			}
		})
		return false;
	}
	var showmodal = function(id)
	{
		var ten = $('#td0_'+id).text();
		var link = $('#td1_'+id).text().replace(' ', '');
		link = link.replace('	', '');
		$('#ntv_id').val(id);
		$('#ung-vien-ten').attr('href', link);
		$('#ung-vien-ten').text(ten);
		$('#modalRespond').modal('show');
	}
	</script>
@stop

app/views/employers/candidates/test.blade.php
@extends('layouts.employer')
@section('title') Quản lý đăng tuyển - VnJobs @stop
@section('content')
	<section class="boxed-content-wrapper clearfix">
		<div class="boxed">
			<div class="heading-image">
				<h2 class="text-orange">Bài kiểm tra sàn lọc</h2>
			</div>
			<button type="button" class="btn btn-lg bg-orange push-bottom">Tạo mới</button>
			<ul class="arrow-right-dark">
				<li><a href="#" class="text-blue"><strong> Vnjobs Standard "Get to know you" Test (English)</strong></a></li>
				<li><a href="#" class="text-blue"><strong> Vnjobs Standard "Get to know you" Test (English)</strong></a></li>
				<li><a href="#" class="text-blue"><strong> Vnjobs Standard "Get to know you" Test (English)</strong></a></li>
				<li><a href="#" class="text-blue"><strong> Vnjobs Standard "Get to know you" Test (English)</strong></a></li>
				<li><a href="#" class="text-blue"><strong> Vnjobs Standard "Get to know you" Test (English)</strong></a></li>
				<li><a href="#" class="text-blue"><strong> Vnjobs Standard "Get to know you" Test (English)</strong></a></li>
			</ul>
		</div>
	</section>
@stop